name: "deployment"
on:
  deployment:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test Observatory
        uses: simonireilly/observatory-github-action@v0.1.0
        id: observatory

      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        with:
          body: "# Deployment ${{ steps.observatory.outputs.observatory-report }}"
