name: "deployment"
on:
  deployment:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test Observatory
        uses: ./
        with:
          web_host: https://observatory-github-action.vercel.app
        id: observatory

      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        with:
          body: "# Deployment ${{ steps.observatory.outputs.observatory-report }}"
