name: 'deployment-status'
on:
  deployment_status:

jobs:
  deployment_status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Observatory
        description: Run the Mozilla observatory tool against the preview URL of the deployment
        uses: ./
        with:
          web_host: ${{ github.event.deployment_status['target_url'] }}
        id: observatory
      - name: Create commit comment
        description: Add a comment to the pull request with the test results
        uses: peter-evans/commit-comment@v1
        with:
          body: '# Deployment Status\n\n${{ steps.observatory.outputs.observatory-report }}'
