name: 'deployment-status'
on:
  deployment_status:

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Observatory
        uses: ./
        with:
          web_host: ${{ github.event.deployment_status['target_url'] }}
        id: observatory
      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        with:
          body: ${{ steps.observatory.outputs.observatory-report }}

