name: 'pull-request-review-comment'
on:
  pull_request_review_comment:
    types: [created, edited]

jobs:
  pull_request_review_comment:
    runs-on: ubuntu-latest
    # if: github.event.pull_request_review_comment.user["login"]
    steps:
      - uses: actions/checkout@v2
      - name: Test Observatory
        uses: ./
        with:
          web_host: https://example.com
        id: observatory
      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        with:
          body: '# Deployment Status _${{ github.event.pull_request_review_comment.user["login"] }}_ ${{ steps.observatory.outputs.observatory-report }}'
