name: "branch"
on:
  pull_request:

jobs:
  static-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test Observatory
        uses: ./
        with:
          web_host: https://1.com/
        id: observatory

      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        with:
          body: "# Branch PR ${{ steps.observatory.outputs.observatory-report }}"
