name: 'branch'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Observatory
        uses: ./
        with:
          web_host: 'github.com'
        id: observatory
      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        with:
          body: ${{ steps.observatory.outputs.observatory-report }}

